### ISSUE TITLE
This repository does not contain "overlay" folder

### ISSUE THREAD

**Issue by kingio** [FydeOS/overlay-tinker#2]
Readme says "follow raspberry instructions" but raspberry repository does contain the required `overlay` folder while this doesn't.

**Comment by nblandfo** [comment]
If you place the contents of chromium_os_for_tinker_board in a folder called overlay-tinker you can use it that way. Or else just rename chromium_os_for_tinker_board to overlay-tinker.

**Comment by kingio** [comment]
ty @nblandfo !
